### ISSUE TITLE
adding 'build' & 'run' functions..

### ISSUE THREAD

**Issue by ffred** [LaurentTreguier/ide-dlang#9]
Hi,
just beginning with D and didn't understand why there was not a 'run' function, so I started learning Atom, this package and post a question on Dlang forum about all that.
after a little search, I now have a 'build' & 'run' working functions selectable with F7.
I posted my modified 'build-provider.js' file on Dlang forum, in case it could be of any help to another beginner.
so not anymore an 'issue', but it would be nice to have those options - and maybe more, like test or don't know what (don't know all I can do with DUB yet) included in the package.
the post on Dlang forum :[ here](https://forum.dlang.org/post/cvqddjjlmkjvbtxndgjb@forum.dlang.org).
thanks..

**Comment by LaurentTreguier** [comment]
The ability to launch build is provided by the [build package](https://github.com/noseglid/atom-build). It has a section for using [custom build commands](https://github.com/noseglid/atom-build#specify-a-custom-build-command), maybe you can use this to have a `dub run` command (or any command you need) ?

**Comment by ffred** [comment]
I added 'dub run', that's what I was saying. but when beginning, it's not the easier way to start.
I will look more at build package, to eventually add my commands here, but I still don't understand why a package made specifically for D development didn't include directly a build and a run command..!?

**Comment by LaurentTreguier** [comment]
Yes, but using the custom JSON/CSON/YAML files, you don't need to modify the extension's code to add commands.
The package was indeed made for D development, but it's mostly just some glue between Atom and a [Language Server](https://microsoft.github.io/language-server-protocol) implementation for D, which is independant from any editor. Since the language server protocol doesn't handle things like compiling and building, I didn't put much thought into it.
I'm also used to VSCode, where those things are very easily specified using VSCode's task system and don't usually need to be added to extensions.

Besides, you'll find that plenty of people in the D community don't use Dub, some will use makefiles (dmd is built using makefiles), or even custom build systems.

**Comment by ffred** [comment]
I understand your point and it's clear that modifying the extension's code is not the better way on a long term, but that was the easiest for me right now.
as a beginner, I was just willing to test a few D code example, not taking half a day looking for an editor/IDE, learn Atom, understand why I can 'build' but I can't 'run', then learn how the build extension is working...... all was new for me and I was thinking that I missed something when I can't found how to 'run' my code.
I really thank you for your work, but I must say that a little more documentation/explanations for beginners would really be helpful. at least say somewhere that you did really the minimal with the build package and we have to add more settings to it.
if I follow your point, why set it for 'build' and why not for 'run' instead. or eventually why set it at all. you could also explain somewhere that we need to add the build package of our choice and configure it. and maybe give an example of setting with the build package for beginners.

[edit:] don't have more time right now, but will look how to configure my settings in the 'build' package.
just one more question; is it possible in this case to disable your build setting to only have my different options..? I see that it's also possible to create a build provider. if I create mine, will it replace yours ??
I know that the 'build' package is not yours, but since you asked to add it, you should know it a little..
thanks again.

**Comment by LaurentTreguier** [comment]
I'll add the `dub run` configuration, since it does make sense to have it by default, and maybe one for `dub test` as well.
The language server is actually my only D project, and it can't be used by simply using `dub run` manually, so that's probably why I didn't think about including it, it's not a command I really used when developing it.
Because the build package is separate, I had put it as a link to it in my `README.md`, where up-to-date and complete docs can be found. This is where info about setting up the build configuration should be looked for.

Regarding your edit question: I don't know, manual configs could either be added to the default ones, or replace them. I'm not an Atom user, I added support for building using this package because it looks like the de facto standard, but I still don't know that much about it.

**Comment by ffred** [comment]
ok, I understand.. that's great. :-)
thanks again.
